services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: design-system
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      # Sesuaikan domain yang digunakan:
      - "traefik.http.routers.design-system.rule=Host(`design.kaltarastats.id`)" 
      # Entrypoint untuk HTTPS (sesuaikan dengan config traefik Anda, misal: websecure)
      - "traefik.http.routers.design-system.entrypoints=web" 
      # Nginx di dalam container berjalan di port 8081
      - "traefik.http.services.design-system.loadbalancer.server.port=8081"

networks:
  proxy_network:
    external: true
